mydashboad/anky_cards_manager/urls.py
"""
Anki cards manager URL Configuration
"""

from django.urls import path

from . import views

app_name = 'anky_cards_manager'

urlpatterns = [
    path('', views.tags_manager_view, name='tags_manager'),
]

mydashboad/mydashboad/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('anky_cards_manager.urls')),
    path('admin/', admin.site.urls),
]

mydashboad/anky_cards_manager/models.py
from django.db import models
from .ankimanager import note_manager

# Create your models here.

class Tag(models.Model):
    """
    Define the tag database parameters.
    """
    name = models.CharField(max_length=5000, unique=True, db_column='tag')
    selected = models.BooleanField(default=False)
    concept_selected = models.BooleanField(default=False)
    procedure_selected = models.BooleanField(default=False)
    culturegenerale_selected = models.BooleanField(default=False)
    red_selected = models.BooleanField(default=False)

    special_tags = ["Concept", "Procedure", "CultureGénérale", "TableauBlanc"]

    def __str__(self):
        return self.name

    class Meta:
        ordering= ['name']

    @classmethod
    def update_tags_info(cls):
        """
        synchronize the tags recorded in the database with the tags in use in Anki
        """
        special_tags = ["Concept", "Procedure", "CultureGénérale", "TableauBlanc"]
        for name in special_tags:
            cls.objects.filter(name=name).delete()
        db_tag_list = {tag.name for tag in cls.objects.all() if tag.name not in special_tags}
        anki_tag_list = {elt for elt in note_manager.usedTagsList()}
        new_db_tags = anki_tag_list - db_tag_list
        for elt in new_db_tags:
            cls.objects.create(
                name=elt,
                selected=False,
                concept_selected=False,
                procedure_selected=False,
                culturegenerale_selected=False,
                red_selected=False)
        old_db_tags = db_tag_list - anki_tag_list
        for elt in old_db_tags:
            cls.objects.filter(name=elt).delete()

mydashboad/anky_cards_manager/views.py
from django.shortcuts import render
from .models import Tag
from .ankimanager import note_manager, util


# Create your views here.

def empty_study_deck():
    study_deck = "AAA_Study_Deck"
    study_deck_notes = note_manager.findNotesUsingFilter('deck:{}'.format(study_deck))
    study_deck_tags = [elt for elt in note_manager.extractTagsFromNotes(study_deck_notes) if
                        elt not in Tag.special_tags]
    decks = note_manager.usedDecksList()
    for tag in study_deck_tags:
        if tag not in decks:
            continue
        else:
            note_manager.cardsWithTagsmoveToDeck(tag_list=[tag], new_deck=tag)
    alert = ""
    remaining_study_deck_notes = note_manager.findNotesUsingFilter('deck:{}'.format(study_deck))
    if len(remaining_study_deck_notes) != 0:
        alert = "We were not able to find an host deck for all the notes of AAA_Study_Deck. " \
                "Every note should contain at least one tag corresponding to a deck name"
    return alert

def synchronize_cards():

    study_deck = "AAA_Study_Deck"
    decks = note_manager.usedDecksList()
    if study_deck not in decks:
        note_manager.createDeck(study_deck)

    alert = empty_study_deck()

    i = 0
    for elt in Tag.objects.all():
        i += 1
        if elt.selected == False\
        and elt.concept_selected == False\
        and elt.procedure_selected == False\
        and elt.culturegenerale_selected == False\
        and elt.red_selected == False :
            pass
        else:
            tag_list = [elt.name]
            if elt.selected:
                note_manager.cardsWithTagsmoveToDeck(tag_list=tag_list,
                                                     new_deck=study_deck,
                                                     red=elt.red_selected)
            else :
                if elt.concept_selected:
                    note_manager.cardsWithTagsmoveToDeck(
                        tag_list=tag_list + ["Concept"],
                        new_deck=study_deck,
                        red=elt.red_selected
                    )
                if elt.procedure_selected:
                    note_manager.cardsWithTagsmoveToDeck(
                        tag_list=tag_list + ["Procedure"],
                        new_deck=study_deck,
                        red=elt.red_selected
                    )
                if elt.culturegenerale_selected:
                    note_manager.cardsWithTagsmoveToDeck(
                        tag_list=tag_list + ["CultureGénérale"],
                        new_deck=study_deck,
                        red=elt.red_selected
                    )
    return alert


def tags_manager_view(request):
    alert = ""

    if request.method == 'POST':
        data = request.POST.dict()
        data.pop("csrfmiddlewaretoken")
        Tag.objects.all().update(
            selected=False,
            concept_selected=False,
            procedure_selected=False,
            culturegenerale_selected=False,
            red_selected=False
        )
        for key, value in data.items():
            tag = key.rsplit('.', maxsplit=1)
            if tag[1] == 'selected':
                Tag.objects.filter(name=tag[0]).update(selected=True)
            elif tag[1] == 'concept_selected':
                Tag.objects.filter(name=tag[0]).update(concept_selected=True)
            elif tag[1] == 'procedure_selected':
                Tag.objects.filter(name=tag[0]).update(procedure_selected=True)
            elif tag[1] == 'culturegenerale_selected':
                Tag.objects.filter(name=tag[0]).update(culturegenerale_selected=True)
            elif tag[1] == 'red_selected':
                Tag.objects.filter(name=tag[0]).update(red_selected=True)
        alert = synchronize_cards()

    elif request.method == 'GET':
        Tag.update_tags_info()

    tags = Tag.objects.all()
    context = {
        'tags' : tags,
        'alert' : alert,
    }

    return render(request, 'anky_cards_manager/tags_manager.html', context)

mydashboad/anky_cards_manager/templates/anky_cards_manager/base.html
<!DOCTYPE html>    <!-- Essential line which indicate it is an HTML page -->

<html lang="en">



    <head>

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width">
        <meta name="description" content="">
        <meta name="author" content="">

        {% load static %}

        <title>{% block title %}Personal Dashboard{% endblock %}</title>


        <link rel="stylesheet" type="text/css" href="{% static 'anky_cards_manager/css/bootstrap.min.css' %}" />

    </head>



    <body>

        <div class="container">
            <div class="row justify-content-center">
                {% block content %}{% endblock %}
            </div>
        </div>

    </body>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block javascript %}{% endblock %}

</html>

mydashboad/anky_cards_manager/templates/anky_cards_manager/tags_manager.html
{% extends 'anky_cards_manager/base.html' %}


{% block content %}

    {% include 'anky_cards_manager/tags_manager_form.html' %}

{% endblock %}

mydashboad/anky_cards_manager/templates/anky_cards_manager/tags_manager_form.html
<form method="post" action="{% url 'anky_cards_manager:tags_manager' %}" id="tag_manager_table_form">

{% csrf_token %}

    <table class="table table-striped table-sm table-bordered">
        <thead style="text-align:center">
            <tr>
                <th scope="col">Tag</th>
                <th scope="col">Full deck</th>
                <th scope="col">Only fundamental concepts</th>
                <th scope="col">Only general rules for implementation and examples</th>
                <th scope="col">General Knowledge</th>
                <th scope="col">Only red flaged cards</th>
            </tr>
        </thead>
        <tbody style="text-align:center" id="tag_manager_table_body">
            {% for tag in tags %}
            <tr>
                <th scope="row">{{ tag.name }}</th>

                {% if tag.selected %}
                    <td><input class="form-check-input" type="checkbox" name="{{ tag.name }}.selected" id="{{ tag.name }}.selected" checked/></td>
                {% else %}
                    <td><input class="form-check-input" type="checkbox" name="{{ tag.name }}.selected" id="{{ tag.name }}.selected"/></td>
                {% endif %}

                {% if tag.concept_selected %}
                    <td><input class="form-check-input" type="checkbox" name="{{ tag.name }}.concept_selected" id="{{ tag.name }}.concept_selected" checked/></td>
                {% else %}
                    <td><input class="form-check-input" type="checkbox" name="{{ tag.name }}.concept_selected" id="{{ tag.name }}.concept_selected"/></td>
                {% endif %}

                {% if tag.procedure_selected %}
                    <td><input class="form-check-input" type="checkbox" name="{{ tag.name }}.procedure_selected" id="{{ tag.name }}.procedure_selected" checked/></td>
                {% else %}
                    <td><input class="form-check-input" type="checkbox" name="{{ tag.name }}.procedure_selected" id="{{ tag.name }}.procedure_selected"/></td>
                {% endif %}

                {% if tag.culturegenerale_selected %}
                    <td><input class="form-check-input" type="checkbox" name="{{ tag.name }}.culturegenerale_selected" id="{{ tag.name }}.culturegenerale_selected" checked/></td>
                {% else %}
                    <td><input class="form-check-input" type="checkbox" name="{{ tag.name }}.culturegenerale_selected" id="{{ tag.name }}.culturegenerale_selected"/></td>
                {% endif %}

                {% if tag.red_selected %}
                    <td><input class="form-check-input" type="checkbox" name="{{ tag.name }}.red_selected" id="{{ tag.name }}.red_selected" checked/></td>
                {% else %}
                    <td><input class="form-check-input" type="checkbox" name="{{ tag.name }}.red_selected" id="{{ tag.name }}.red_selected"/></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" id="modal_tag_manager_submit">Submit changes</button>
    <button type="reset" class="btn btn-primary" id="tag_manager_reset">Reset tags info</button>
    <div id="tag_manager_submit_alert"><em>{{ alert }}</em></div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Safety step for a better Anki experience</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              Check that Anki is open on the homepage and not busy adding/modifying notes.
              Then, click on "Confirm submission"
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary" id="tag_manager_submit">Confirm submission</button>
          </div>
        </div>
      </div>
    </div>

</form>